export const barChartData = [
  { month: 'Jan', occupancyRate: 85 },
  { month: 'Feb', occupancyRate: 86 },
  { month: 'Mar', occupancyRate: 89 },
  { month: 'Apr', occupancyRate: 84 },
  { month: 'May', occupancyRate: 89 },
  { month: 'Jun', occupancyRate: 90 },
  { month: 'Jul', occupancyRate: 92 },
  { month: 'Aug', occupancyRate: 93 },
  { month: 'Sep', occupancyRate: 92 },
  { month: 'Oct', occupancyRate: 94 },
  { month: 'Nov', occupancyRate: 93 },
  { month: 'Dec', occupancyRate: 95 },
];

export const pieDataMonth = [
  { name: 'Occupied', value: 1202 },
  { name: 'Vacant', value: 24 },
];

export const pieDataYear = [
  { name: 'Occupied', value: 1195 },
  { name: 'Vacant', value: 35 },
];

export const mockStatsData = [
  { title: 'Portfolio', value: '$1,200,000' },
  { title: 'Community', value: '1,500 Members' },
  { title: 'Assets', value: '$3,500,000' },
  { title: 'Settings', value: 'Updated' },
];

const getRandomSavingsGoal = () =>
  Math.floor(Math.random() * (3500 - 1000 + 1)) + 1000;

export const mockTableData = [
  {
    unit: '101',
    name: 'John Doe',
    renewalDate: '2023-12-01',
    vivaScore: 95,
    savingsProgress: 80,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '102',
    name: 'Jane Smith',
    renewalDate: '2023-11-15',
    vivaScore: 90,
    savingsProgress: 60,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '103',
    name: 'Sam Johnson',
    renewalDate: '2023-10-20',
    vivaScore: 85,
    savingsProgress: 70,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '104',
    name: 'Chris Lee',
    renewalDate: '2023-09-30',
    vivaScore: 92,
    savingsProgress: 90,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '105',
    name: 'Patricia Brown',
    renewalDate: '2023-08-25',
    vivaScore: 88,
    savingsProgress: 50,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '106',
    name: 'Michael Davis',
    renewalDate: '2023-07-14',
    vivaScore: 94,
    savingsProgress: 85,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '107',
    name: 'Linda Wilson',
    renewalDate: '2023-06-10',
    vivaScore: 91,
    savingsProgress: 75,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '108',
    name: 'Robert Martinez',
    renewalDate: '2023-05-05',
    vivaScore: 89,
    savingsProgress: 65,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '109',
    name: 'Mary Anderson',
    renewalDate: '2023-04-22',
    vivaScore: 87,
    savingsProgress: 55,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '110',
    name: 'James Taylor',
    renewalDate: '2023-03-18',
    vivaScore: 93,
    savingsProgress: 95,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '111',
    name: 'Barbara Thomas',
    renewalDate: '2023-02-12',
    vivaScore: 86,
    savingsProgress: 45,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '112',
    name: 'William Jackson',
    renewalDate: '2023-01-08',
    vivaScore: 90,
    savingsProgress: 70,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '113',
    name: 'Elizabeth White',
    renewalDate: '2022-12-25',
    vivaScore: 92,
    savingsProgress: 80,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '114',
    name: 'David Harris',
    renewalDate: '2022-11-20',
    vivaScore: 88,
    savingsProgress: 60,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '115',
    name: 'Jennifer Clark',
    renewalDate: '2022-10-15',
    vivaScore: 85,
    savingsProgress: 50,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '116',
    name: 'Richard Lewis',
    renewalDate: '2022-09-10',
    vivaScore: 94,
    savingsProgress: 90,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '117',
    name: 'Susan Robinson',
    renewalDate: '2022-08-05',
    vivaScore: 89,
    savingsProgress: 65,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '118',
    name: 'Joseph Walker',
    renewalDate: '2022-07-01',
    vivaScore: 87,
    savingsProgress: 55,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '119',
    name: 'Karen Hall',
    renewalDate: '2022-06-26',
    vivaScore: 91,
    savingsProgress: 75,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '120',
    name: 'Charles Allen',
    renewalDate: '2022-05-21',
    vivaScore: 93,
    savingsProgress: 85,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '121',
    name: 'Nancy Young',
    renewalDate: '2022-04-16',
    vivaScore: 86,
    savingsProgress: 45,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '122',
    name: 'Daniel King',
    renewalDate: '2022-03-11',
    vivaScore: 90,
    savingsProgress: 70,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '123',
    name: 'Lisa Wright',
    renewalDate: '2022-02-06',
    vivaScore: 92,
    savingsProgress: 80,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '124',
    name: 'Matthew Scott',
    renewalDate: '2022-01-01',
    vivaScore: 88,
    savingsProgress: 60,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '125',
    name: 'Betty Green',
    renewalDate: '2021-12-27',
    vivaScore: 85,
    savingsProgress: 50,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '126',
    name: 'Mark Adams',
    renewalDate: '2021-11-22',
    vivaScore: 94,
    savingsProgress: 90,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '127',
    name: 'Sandra Baker',
    renewalDate: '2021-10-17',
    vivaScore: 89,
    savingsProgress: 65,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '128',
    name: 'Steven Gonzalez',
    renewalDate: '2021-09-12',
    vivaScore: 87,
    savingsProgress: 55,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '129',
    name: 'Donna Nelson',
    renewalDate: '2021-08-07',
    vivaScore: 91,
    savingsProgress: 75,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '130',
    name: 'Paul Carter',
    renewalDate: '2021-07-03',
    vivaScore: 93,
    savingsProgress: 85,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '131',
    name: 'Carol Mitchell',
    renewalDate: '2021-06-28',
    vivaScore: 86,
    savingsProgress: 45,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '132',
    name: 'Kevin Perez',
    renewalDate: '2021-05-23',
    vivaScore: 90,
    savingsProgress: 70,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '133',
    name: 'Michelle Roberts',
    renewalDate: '2021-04-18',
    vivaScore: 92,
    savingsProgress: 80,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '134',
    name: 'Brian Turner',
    renewalDate: '2021-03-13',
    vivaScore: 88,
    savingsProgress: 60,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '135',
    name: 'Dorothy Phillips',
    renewalDate: '2021-02-08',
    vivaScore: 85,
    savingsProgress: 50,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '136',
    name: 'Jason Campbell',
    renewalDate: '2021-01-03',
    vivaScore: 94,
    savingsProgress: 90,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '137',
    name: 'Helen Parker',
    renewalDate: '2020-12-29',
    vivaScore: 89,
    savingsProgress: 65,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '138',
    name: 'Ryan Evans',
    renewalDate: '2020-11-24',
    vivaScore: 87,
    savingsProgress: 55,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '139',
    name: 'Amy Edwards',
    renewalDate: '2020-10-19',
    vivaScore: 91,
    savingsProgress: 75,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '140',
    name: 'Gary Collins',
    renewalDate: '2020-09-14',
    vivaScore: 93,
    savingsProgress: 85,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '141',
    name: 'Angela Stewart',
    renewalDate: '2020-08-09',
    vivaScore: 86,
    savingsProgress: 45,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '142',
    name: 'Timothy Sanchez',
    renewalDate: '2020-07-05',
    vivaScore: 90,
    savingsProgress: 70,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '143',
    name: 'Sharon Morris',
    renewalDate: '2020-06-30',
    vivaScore: 92,
    savingsProgress: 80,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '144',
    name: 'Frank Rogers',
    renewalDate: '2020-05-25',
    vivaScore: 88,
    savingsProgress: 60,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '145',
    name: 'Cynthia Reed',
    renewalDate: '2020-04-20',
    vivaScore: 85,
    savingsProgress: 50,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '146',
    name: 'Scott Cook',
    renewalDate: '2020-03-15',
    vivaScore: 94,
    savingsProgress: 90,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '147',
    name: 'Rebecca Morgan',
    renewalDate: '2020-02-10',
    vivaScore: 89,
    savingsProgress: 65,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '148',
    name: 'Eric Bell',
    renewalDate: '2020-01-05',
    vivaScore: 87,
    savingsProgress: 55,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '149',
    name: 'Katherine Murphy',
    renewalDate: '2019-12-31',
    vivaScore: 91,
    savingsProgress: 75,
    savingsGoal: getRandomSavingsGoal(),
  },
  {
    unit: '150',
    name: 'Larry Bailey',
    renewalDate: '2019-11-26',
    vivaScore: 93,
    savingsProgress: 85,
    savingsGoal: getRandomSavingsGoal(),
  },
];
